// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnOsZNP5D0kJXVATyAw8NEYbklN6eviss',
    appId: '1:1036471330400:web:66a2acebc6d113be11c505',
    messagingSenderId: '1036471330400',
    projectId: 'ecommeredi',
    authDomain: 'ecommeredi.firebaseapp.com',
    storageBucket: 'ecommeredi.appspot.com',
    measurementId: 'G-HLQZDFCH2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP0p2kDQYDRFAk-PzyRj1GO_o4iGAh6hg',
    appId: '1:1036471330400:android:3a8d02584d62e47311c505',
    messagingSenderId: '1036471330400',
    projectId: 'ecommeredi',
    storageBucket: 'ecommeredi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhIxtYEKkBp1xd7mk_PmfecrQKp8nRqLM',
    appId: '1:1036471330400:ios:255f588f66b0302911c505',
    messagingSenderId: '1036471330400',
    projectId: 'ecommeredi',
    storageBucket: 'ecommeredi.appspot.com',
    iosClientId: '1036471330400-c1erus50708veu3fln67arm4a01imouq.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceFirebaseUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhIxtYEKkBp1xd7mk_PmfecrQKp8nRqLM',
    appId: '1:1036471330400:ios:255f588f66b0302911c505',
    messagingSenderId: '1036471330400',
    projectId: 'ecommeredi',
    storageBucket: 'ecommeredi.appspot.com',
    iosClientId: '1036471330400-c1erus50708veu3fln67arm4a01imouq.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceFirebaseUser',
  );
}
